name: argocd-apps
descriptions: a helm chart for argocd
version: 1.0.0
appVersion: v3
kubeVersion: ">=1.9.0-0"

dependencies: 
  - name: argocd-apps
    version: 2.0.2
    repository: https://argoproj.github.io/argo-helm 
 
