name: sealed-secrets
descriptions: a helm chart for sealed-secrets
version: 1.0.0
appVersion: 0.33.1
kubeVersion: ">=1.9.0-0"
home: https://bitnami-labs.github.io/sealed-secrets
appVersion: v3

dependencies: 
  - name: sealed-secrets
    version: 2.17.9
    repository: https://bitnami-labs.github.io/sealed-secrets
