ingress:
  enabled: true

persistentVolumeClaim:
  enabled: true

podDnsConfig:
  enabled: true
  policy: "None"
  nameservers:
  - 127.0.0.1
  - 8.8.8.8

admin:
  enabled: true
  existingSecret: "pihole-admin"
  adminpasswordKey: "password" 

adminEncryptedPassword: AgAj/XfpDEQS/fL058xSCLvXmCrgBnN3fDysOGweDvC9lOr6cEwU134YzhR2hOsrDYXTT5F7tbUOqgfRPti4Tcv1Db9B00KwpU21exY6q7btoCSHkIKetnJY7wmenupVD4SjuNfwFbvNBK0dpK82exwQByLATIQux+5aEMuG4YXYO6/jXSSkpTrWC2tb3RlKiaMWs9zzgLBWFfB3KMaukog6chHEeBfF2q8kzQKUphvq4A/rXLoTISRMJzJulw2lPmNTaLmMNs53NaSgYn7cgjApy+birsu4MhIdLzzTqu4Es8+f43ZqWXDo50KzlPDurtXKE3HC0i98AWaYcttzk0hKulVzLO6DPrqP51lY6sljMnk8Y3xMKG55j6Yvb/gvkcLz9HBYSLqe9PYjJPn28QlmqwJgv6SjEBr4W+I1ltN8lvyIosdWzQfwl5HqVneHzGYaJlL7ylJtIk1LUg6Za3y1se6ldAbRcJFjSkI+wsUFLnu6OU6f+7uu1ZrKotSXp6VSatFw/4F4S+iXn4zgQYWFxakoniqWI2fsBxhvTi1HWHHqOnDFXYI7arzN8EHlnrpMDU6+OQe9CRgWM4hJu7q2XAoUvEodqRnP9wR/wIpYi0Rz1pWAv358BrWVPx8Pfz0STCg6nZBk1hH0s66IKhEY6p1UFBRBZNA31rst4P366OFpSGZ7oPtzOVkIZ0C7zxXgEZasZRmQU6OEAjmmlpkq1yIW3w==

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

extraEnvVars: {
  DNSMASQ_USER: "root"
}
