name: cert-manager
descriptions: a helm chart for cert-manager
version: 1.0.0
appVersion: 0.33.1
kubeVersion: ">=1.9.0-0"
apiVersion: v3
appVersion: v1.19.1

dependencies: 
  - name: cert-manager
    version: v1.19.1
    repository: https://charts.jetstack.io
